### ISSUE TITLE
monitor.hex crashes with invalid instruction

### ISSUE THREAD

**Issue by ghost** [raybellis/usim#2] opened 2018-02-24 03:28 UTC
After building on Fedora 27, the monitor.hex crashes with the following error:
```
[amr@localhost usim]$ ./usim bin/monitor.hex 
System loaded and ready
 CC:09  A:6b  B:90 DP:00  X:e0ff  Y:0000
 CC:00  A:69  B:81 DP:00  X:e0ff  Y:0000

invalid instruction : pc = [e01e], ir = [0013]
```

The tbasic.hex does run fine though. I manually installed the x11 dependencies and it built with no errors, which is great. Just wanted to let you know about this bug, and if I can help, let me know.

**Comment by raybellis** [comment] 2018-02-24 09:28
It's not a "bug" as such - the `monitor` file includes use of the `SYNC` instruction which is currently unimplemented (hence this is a duplicate of #1)

**Closed as completed by raybellis** 2018-02-24 09:28 UTC
